#!/usr/bin/env python3
"""
Setup Wizard for Voice Dictation System
Guides users through initial configuration
"""

import os
import sys
from pathlib import Path

def print_header(text):
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60)

def print_step(number, text):
    print(f"\n[Step {number}] {text}")

def main():
    print_header("Voice Dictation System - Setup Wizard")
    print("\nWelcome! This wizard will help you set up your dictation system.")
    print("The setup process takes about 2 minutes.\n")

    input("Press Enter to continue...")

    # Get script directory
    script_dir = Path(__file__).parent.absolute()
    env_path = script_dir / ".env"

    # Step 1: Check for existing .env
    print_step(1, "Checking for existing configuration")

    if env_path.exists():
        print(f"✓ Found existing .env file at: {env_path}")
        overwrite = input("\nDo you want to reconfigure? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("\nKeeping existing configuration. Setup complete!")
            return
    else:
        print("No .env file found. Creating new configuration...")

    # Step 2: Get OpenAI API Key
    print_step(2, "OpenAI API Key Setup")
    print("\nYou need an OpenAI API key to use this service.")
    print("The key is used to clean up your transcripts using GPT-4o-mini.")
    print("\nTo get your API key:")
    print("  1. Visit: https://platform.openai.com/api-keys")
    print("  2. Sign in or create an account")
    print("  3. Click 'Create new secret key'")
    print("  4. Copy the key (it starts with 'sk-')")

    api_key = ""
    while True:
        print("\n")
        api_key = input("Paste your OpenAI API key here: ").strip()

        if not api_key:
            print("❌ API key cannot be empty")
            continue

        if not api_key.startswith("sk-"):
            print("⚠️  Warning: OpenAI keys usually start with 'sk-'")
            confirm = input("Are you sure this is correct? (y/N): ").strip().lower()
            if confirm != 'y':
                continue

        break

    # Step 3: Write .env file
    print_step(3, "Saving configuration")

    env_content = f"""# OpenAI API Key for Dictation Service
# Generated by setup wizard

OPENAI_API_KEY={api_key}
"""

    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        print(f"✓ Configuration saved to: {env_path}")
    except Exception as e:
        print(f"❌ Error saving configuration: {e}")
        sys.exit(1)

    # Step 4: Verify dependencies
    print_step(4, "Checking dependencies")

    missing_deps = []
    deps_to_check = [
        ('sounddevice', 'sounddevice'),
        ('soundfile', 'soundfile'),
        ('numpy', 'numpy'),
        ('pynput', 'pynput'),
        ('whisper', 'openai-whisper'),
        ('openai', 'openai'),
        ('dotenv', 'python-dotenv'),
    ]

    for module_name, package_name in deps_to_check:
        try:
            __import__(module_name)
            print(f"  ✓ {package_name}")
        except ImportError:
            print(f"  ✗ {package_name} (missing)")
            missing_deps.append(package_name)

    if missing_deps:
        print(f"\n⚠️  Missing dependencies: {', '.join(missing_deps)}")
        print("\nPlease run the installer:")
        print("  bash install.sh")
    else:
        print("\n✓ All dependencies installed!")

    # Step 5: Permissions reminder
    print_step(5, "macOS Permissions")
    print("\nWhen you first run the dictation service, macOS will ask for:")
    print("  • Microphone access - to record your voice")
    print("  • Accessibility access - to detect keyboard and paste text")
    print("\nMake sure to click 'OK' or 'Allow' for these permissions!")

    # Done!
    print_header("Setup Complete!")
    print("\nYour dictation system is configured and ready to use.\n")
    print("To start the service:")
    print("  bash start_dictation.sh")
    print("\nControls:")
    print("  • Press Control twice quickly → Start recording")
    print("  • Press Control once → Stop and transcribe")
    print("\n")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
